const data = new Date()
console.log(data)
console.log(data.getDay())
console.log(data.getDate())
console.log(data.getMonth())
console.log(data.getTime())
console.log(data.getFullYear())
console.log(data.getHours())
console.log(data.getUTCHours())
data.setDate(22)
console.log(data)
console.log(data.toDateString)
console.log(data.toISOString)
console.log(data.toLocaleDateStringq)